name: CI

on:
  workflow_dispatch:

env:
    WINSYSTEM: '8.1'

jobs:
  build:
    runs-on: windows-2022
    steps:   
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        release: false
        update: true
        install: make pkg-config diffutils    

    - name: Set ENV
      shell: cmd
      run: |
        set Path=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%path% 

    - name: Install polib      
      run: |
        pip install polib                  

    - name: Setup Toolchain
      run: |
        curl -OL http://files.1f0.de/mingw/mingw-w64-gcc-11.2-stable-r36.7z
        &'C:\Program Files\7-Zip\7z.exe' x *.7z -o'C:\msys64\mingw64' 
    
    - name: Install Yasm
      run: |
        curl -OL http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe
        mv yasm-1.3.0-win64.exe C:\msys64\usr\bin\yasm.exe                  

    - name: Install Nasm
      run: |
        curl -OL https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip
        &'C:\Program Files\7-Zip\7z.exe' x nasm-2.15.05-win64.zip -o'D:'
        mv 'D:\nasm-2.15.05\nasm.exe' 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC'
    
    - name: Install Windows 8.1 SDK
      if: env.WINSYSTEM == '8.1'
      shell: powershell
      run: |
        Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
        Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit"  
  
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0    
        submodules: true
      
    - name: Checkout modules
      run: git submodule update --init --recursive         
   
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1 

    - name: Build the package (x64)
      env:
        MPCHC_MSYS: 'C:\msys64'
        MPCHC_MINGW64: 'C:\msys64\mingw64'
        MSYS2_PATH_TYPE: inherit
        MPCBE_WINSDK_VER: ${{ env.WINSYSTEM }}
        MPCHC_GIT: 'C:\Program Files\Git'
      shell: cmd
      run: |
        msbuild .\mpc-hc.sln /m /p:Configuration=Release
        msbuild .\mpciconlib.sln 
        msbuild .\mpcresources.sln

    - name: Upload 7z archives (x64)
      uses: actions/upload-artifact@v2
      with:
        name: MPC-HC 
        path: bin\mpc-hc_x86   
